trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: terraform
  steps:
  - task: Checkout@2

  - task: AzureCLI@2
    inputs:
      azureSubscription: '$(AZURE_SUBSCRIPTION_ID)'
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        az login --identity

  - task: UseTerraform@0
    inputs:
      terraformVersion: '1.0.0'

  - script: terraform init
    displayName: 'Terraform Init'

  - script: terraform plan
    displayName: 'Terraform Plan'

  - script: terraform apply -auto-approve
    displayName: 'Terraform Apply'